### ISSUE TITLE
LINE bot 連携

### ISSUE THREAD

**Issue by SuzukiTakamasa** [SuzukiTakamasa/HouseholdApp#6]
- [ ] LINE Developer console上でチャネル作成
- [ ] Vercel上にデプロイおよびwebhook URL作成

**Comment by SuzukiTakamasa** [comment]
```
import * as express from 'express';
import * as line from '@line/bot-sdk';

const app = express();

const config = {
  channelAccessToken: process.env.CHANNEL_ACCESS_TOKEN,
  channelSecret: process.env.CHANNEL_SECRET,
};

const client = new line.Client(config);

// Firebase Admin SDKを初期化
if (!admin.apps.length) {
    admin.initializeApp({
        credential: admin.credential.cert({
            projectId: process.env.FIREBASE_PROJECT_ID,
            clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
            privateKey: process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, '\n'),
        }),
        databaseURL: `https://${process.env.FIREBASE_PROJECT_ID}.firebaseio.com`
    });
}

app.post('/send-message', (req, res) => {

  const snapshot = await db.collection('your_collection').get();
  const data = snapshot.docs.map(doc => doc.data());

  const message = {
    type: 'text',
    text: '今月の請求金額は以下です\n${data.amount}', //temporary
  };

  client.pushMessage(process.env.LINE_USER_ID, message)
    .then(() => {
      res.status(200).json({ message: 'Message sent successfully' });
    })
    .catch((err) => {
      console.error(err);
      res.status(500).json({ message: 'Error sending message' });
    });
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Listening on port ${port}`);
});

```

**Comment by SuzukiTakamasa** [comment]
```
// vercel.jsonの値
{
  "version": 2,
  "builds": [
    {
      "src": "api/**/*.ts",
      "use": "@vercel/node",
      "config": {
        "maxLambdaSize": "50mb"
      }
    }
  ],
  "routes": [
    {
      "src": "/api/send-message",
      "dest": "/api/send-message.ts",
      "methods": ["POST"]
    }
  ],
```

**Comment by SuzukiTakamasa** [comment]
無料でcron jobを実行してくれるサイト
https://cron-job.org/en/

**Comment by SuzukiTakamasa** [comment]
メモ：
特定のUserIDに対してのみメッセージを送信する
```
const userIds = [process.env.USER_ID_T, process.env.USER_ID_Y]
userIds.forEach(userId => {
      if (userId) {
        client.pushMessage(userId, { type: 'text', text: message })
          .catch(err => console.error(err));
      }
```

**Comment by SuzukiTakamasa** [comment]
ymlの記載例
```
name: Deploy to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'vercel/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./vercel

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./vercel
          vercel-args: '--prod'

```
